### ISSUE TITLE
On a board with not many tasks / projects this works fine for me, but on our production board of about 2 years it wont even open.

### ISSUE THREAD

**Issue by Jieiku** [Chaosmeister/KADIFF#1]
I recently setup kanboard at home to help me get better organized with tasks in my daily life. (one of the reason I found all your plugins recently.)

At my work on our production Kanboard install with about 40 projects and hundreds of tasks, the activity stream will not open when you click "My activity stream" Once I uninstalled this plugin I could once again view the activity stream.

There is sensitive information in our kanboard but if there is anything I can do on my end that would help you debug the issue then let me know.

**Comment by Chaosmeister** [comment]
you could try to find the logs of your webserver and have a look at the errorcode/message. 
If it's something simple, we may be able to resolve it, but this plugin just wraps php-diff so support is a bit limited

**Comment by Jieiku** [comment]
Sorry for not responding sooner, here is what I found:

`sudo tail -f /var/log/nginx/error.log`

```
=ActivityController&action=user HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "kanban.example.com"
2021/12/04 10:32:35 [error] 196#196: *42136 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: description in /var/www/kanboard/plugins/KADIFF/Plugin.php on line 120PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Jfcherng\Diff\Differ::setOldNew() must be of the type array, null given, called in /var/www/kanboard/plugins/KADIFF/src/DiffHelper.php on line 143 and defined in /var/www/kanboard/plugins/KADIFF/src/Differ.php:140
Stack trace:
#0 /var/www/kanboard/plugins/KADIFF/src/DiffHelper.php(143): Jfcherng\Diff\Differ->setOldNew()
#1 /var/www/kanboard/plugins/KADIFF/Plugin.php(120): Jfcherng\Diff\DiffHelper::calculate()
#2 /var/www/kanboard/app/Core/Filter/QueryBuilder.php(83): Kanboard\Plugin\KADIFF\MyFormatter->format()
#3 /var/www/kanboard/app/Helper/ProjectActivityHelper.php(85): Kanboard\Core\Filter\QueryBuilder->format()
#4 /var/www/kanboard/app/Controller/ActivityController.php(24): Kanboard\Helper\ProjectActivityHelper->getProjectsEvents()
#5 /var/www/kanboard/app/Core/Controller/Runner.php(77): Kanboard\Controller\ActivityController->user()
#6 /var/www/kanboard/app/Core/Controller/Runner.php(31): Kanboard\Core\Controller\Runner-" while reading response header from upstream, client: 10.7.1.80, server: kanban.example.com, request: "GET /?controller=ActivityController&action=user HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "kanban.example.com"
```

**Comment by Jieiku** [comment]
oh you know what. I think it might be caused by creating a task that does not have a description.

I do have some of those where we are just using the title of the task and the description is empty (null)

So maybe your plugin just needs to check if the description is null before trying to diff it.

you could create a task by only setting a title, then edit that task, only changing the title, and see if your able to reproduce.

**Comment by Chaosmeister** [comment]
ahh I see,  I will fix it in a moment. thanks for the report!

**Comment by Chaosmeister** [comment]
so i just tried to create a testcase for this, but it all worked as expected  

![image](https://user-images.githubusercontent.com/13346344/144722160-19f5fac6-1085-4ef1-a625-b19905fd3b55.png)

looks like there is something else to it

**Comment by Chaosmeister** [comment]
ah I misread, but editing the title isn't even diffed at the moment.
this also doesn't cause any issues on my side

**Comment by Chaosmeister** [comment]
I just pushed 2 changes that might help in your case and also fix a cornercase when the description was cleared out completely.
this is now displayed correctly.

I updated the release so un- +reinstalling the plugin should refresh it for you

**Comment by Jieiku** [comment]
The new version fixed the issue on both of my boards, thank you very much!
