### ISSUE TITLE
Sometimes KADIFF shows you a diff between two completely different tasks.

### ISSUE THREAD

**Issue by Jieiku** [Chaosmeister/KADIFF#2]
I was looking over the Activity Feed and sometimes KADIFF shows you a diff between two completely different tasks.

I modified the description of Task1
I modified the Title of Task1
I modified the Title of Task1 again
I modified the Title of Task2
I moved Task2 to the Done column
**Change assignee of task2**

This resulted in a KADIFF for the description between Task1 and Task2.
It should have been a KADIFF of Task2 old and Task2 new

I am not sure if this same sequence of events will always reproduce this error.
But If you do a lot of edits and pay attention to the activity feed then you will probably see it reproduced eventually.

**Comment by Chaosmeister** [comment]
are you in the activitystream of a single task or of the project?  
I've only tested the task activity stream diffs so far

**Comment by Jieiku** [comment]
wait i missed a step, let me edit my earlier post, i changed the assignment of a task.

### It was actually setting a new assignee that caused it.

I was viewing the activity stream here: https://kanboard.example.com/?controller=ActivityController&action=user

going to try checking the task now.

Yes In the TASK activity stream it is correct, its only in the user stream that it is not.

**Comment by Chaosmeister** [comment]
ahh  I didn't even realize there's a user activity stream

I'll take a look

**Comment by Jieiku** [comment]
hey check this out: https://github.com/BlueTeck/kanboard_plugin_bigboard/pull/36

I add a few links that simplify site navigation, and it closes one of my issue reports for bigboard.

One of the links is the activity feed. (normally you would get to this feed from the "My activity stream" link in your Dashboard, or at the sites base URL)

**Comment by Chaosmeister** [comment]
I was able to reproduce it. 🎉

**Comment by Chaosmeister** [comment]
yeah that is fixable.  
currently the formatter only expects changes in a single task

**Comment by Chaosmeister** [comment]
I updated the package

reinstalling will fix the issue ✌️

**Comment by Jieiku** [comment]
Yep, looks good here too! Thank you!
