### ISSUE TITLE
Not directly related to KADIFF, but maybe feature request. Admins Delete Entry in history.

### ISSUE THREAD

**Issue by Jieiku** [Chaosmeister/KADIFF#3]
In the event that somebody accidently puts sensitive information into the description of a post.

It would be good if there were an easy way to delete that entry from the history.

This is more of a feature request, possibly a separate plugin completely.

I figure since you made KADIFF your probably familiar with how the files work and where this information is stored.

I have no idea if something like this is even possible.

**Comment by Chaosmeister** [comment]
There's currently just one way to remove sensitive information from kanboard and it involves deleting the whole task.

If you're admin and have access to the database, you can just delete rows from the tables.  
It is just not user friendly.  
This also may result in other problems somewhere else though if you delete a required row.

I'll take a look at it, when I find some more time ✌️

**Comment by Jieiku** [comment]
Thanks! for now I will delete and recreate the task.

**Comment by Chaosmeister** [comment]
hey, so I gave this a thought and there are basically multiple ways to solve this.

you can either really remove the database entry (where I can't really foresee the effects) or you could "redact" the information, which would keep the entries intact, but censors the sensitive information.

We also have to solve, where to offer this functionality

**Comment by Jieiku** [comment]
Most history trackers like github or discourse, when you view the history you can delete an item/change from the history.
So I picture it being something like this:

![2021-12-13_02-54](https://user-images.githubusercontent.com/106644/145800079-c88ba2c6-ecd5-4b3c-b1c9-e03e2f83c167.png)

Generally history should be self documenting, so maybe just deleting an item from the history is better than allowing to edit it.

Maybe there is a way to link the previous edit to the next edit, then you would not really be missing anything in the history.

So you first edit the offending post to remove the sensitive info. then when you delete an item in the history, it generates a new diff bridging the gap.

For me personally, just being able to delete an entry would suffice. Anything else could be version 2.0 if its too much work to implement more than that now.

**Comment by Jieiku** [comment]
I GOT IT!

When you delete an entry from the history. In the DB just update the entry to whatever the task previously had set.

so task #4 history in db:
1. first task of the day.
2. first task of the day. we need to get the software installed.
3. first task of the day. we need to get the software installed. bank account password is spot123

If you delete the 3rd item from the history. in the db replace its contents with whatever the previous one had, so it becomes:
1. first task of the day.
2. first task of the day. we need to get the software installed.
3. first task of the day. we need to get the software installed.

**Comment by Chaosmeister** [comment]
I'm currently workin on this.

finding a place to inject the button was the most difficult thing yet, but I got that figured out this night:

![image](https://user-images.githubusercontent.com/13346344/146169784-742b8b11-12ab-4707-835e-4ec5ae5f08c7.png)

So there's a button now, which will add a "redacted" flag in the event data.  this (kinda intrusive) way keeps the data alive but allows me to skip the entry in the activitystream.

There are a few things left to define:

* should admins still be able to see the redacted event?
* should you be able to un-redact the event?

**Comment by Jieiku** [comment]
mmm. I mean any of those options could be good options depending on the work environment.

you could add a configuration section for kadiff if you wanted, then redacting data could either be deleted permanently or allow to be restored.

the button you chose looks perfect! good appearance and placement.

**Comment by Chaosmeister** [comment]
nono

this is going to be another standalone plugin, compatible to kadiff. 

I'll have a look at how to add a configurationsetting for the new plugin

**Comment by Jieiku** [comment]
ah gotcha!

I did have one more thought. if somebody is using a tablet, they might accidently hit the button to redact / delete the entry, maybe it should pop up one of those "Are you sure you want to do this?" prompts

**Comment by Chaosmeister** [comment]
Since there's enough space, I offer both buttons (delete & hide) instead of a configurationmenu.
I also chose better icons:

![image](https://user-images.githubusercontent.com/13346344/146206005-c4c1bea2-a6e5-4355-be34-875cf4e2a26c.png)

User view <-> Admin view
![image](https://user-images.githubusercontent.com/13346344/146222346-cf73814b-ca20-4310-b81c-c25bb175b446.png)

**Comment by Jieiku** [comment]
Awesome!!! love it!

**Comment by Chaosmeister** [comment]
did it

https://github.com/Chaosmeister/PAM

**Comment by Chaosmeister** [comment]
Can we close this ticket?

**Comment by sunjam** [comment]
Definitely should be able to closed thanks to the dedicated PAM plugin.  Thank you!
