### ISSUE TITLE
Unclear Installation Procedure

### ISSUE THREAD

**Issue by george-viaud** [Chaosmeister/KADIFF#4]
What is the installation procedure?

I installed via Kanboard plugin menu but am not seeing any diff in Activity Stream of any tickets regardless of large amount of activity.  Activity stream looks normal / vanilla.

I suspect I may have done something wrong during install or there are external dependencies?

Running Kanboard 1.2.21 and KADIFF 1.0.0

Thank you

**Comment by Chaosmeister** [comment]
hey!

did you install the "markdown plus" extension as well?

I added the requirement to the readme

alternatively you can adjust the setting

```php
// Escape html inside markdown text
define('MARKDOWN_ESCAPE_HTML', false);
```

**Comment by george-viaud** [comment]
Bingo!  Thank you - excellent.
